# Generated by Django 5.2.6 on 2025-09-19 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
